from __future__ import annotations


DEFAULT_DEPENDENCY_TIMEOUT_SECONDS = 2.0
DEFAULT_DEPENDENCY_MAX_CONNECTIONS = 20
DEFAULT_DEPENDENCY_MAX_KEEPALIVE_CONNECTIONS = 10
DEFAULT_HTTP_REQUEST_BODY_MAX_BYTES = 1_048_576
DEFAULT_OUTBOX_DELIVERY_MAX_RETRY_COUNT = 3
POSTGRES_CONNECTION_UTILIZATION_WARN_FRACTION = 0.7
POSTGRES_CONNECTION_UTILIZATION_SHED_FRACTION = 0.9
