from __future__ import annotations

REQUIRED_OUTBOX_PROOF_PATHS = {
    "scripts/repository_hygiene/outbox_paths.py",
    "scripts/outbox/broker/__init__.py",
    "scripts/outbox/broker/generate_source_contract_proof.py",
    "scripts/outbox/broker/generate_runtime_execution.py",
    "scripts/outbox/broker/runtime_execution_gate.py",
    "scripts/outbox/broker/source_contract_proof_gate.py",
    "src/app/application/outbox/broker/__init__.py",
    "src/app/application/outbox/broker/runtime_execution.py",
    "src/app/application/outbox/broker/source_contract_proof.py",
    "tests/unit/outbox/broker/__init__.py",
    "tests/unit/outbox/broker/test_readiness_consumption.py",
    "tests/unit/outbox/broker/test_runtime_execution.py",
    "tests/unit/outbox/broker/test_source_contract_proof.py",
    "scripts/outbox/generate_consumer_runtime_execution.py",
    "scripts/outbox/consumer_runtime_execution_gate.py",
    "src/app/application/outbox/consumer_runtime.py",
    "tests/unit/outbox/test_outbox_consumer_runtime_execution.py",
    "tests/unit/outbox/test_outbox_consumer_runtime_readiness.py",
    "scripts/outbox/platform_mesh/__init__.py",
    "scripts/outbox/platform_mesh/generate_source_contract_proof.py",
    "scripts/outbox/platform_mesh/source_contract_proof_gate.py",
    "src/app/application/outbox/platform_mesh/__init__.py",
    "src/app/application/outbox/platform_mesh/source_contract_proof.py",
    "tests/unit/outbox/platform_mesh/__init__.py",
    "tests/unit/outbox/platform_mesh/test_readiness_consumption.py",
    "tests/unit/outbox/platform_mesh/test_source_contract_proof.py",
}
