DROP INDEX IF EXISTS idx_idea_outbox_recovery_requested_at;
DROP INDEX IF EXISTS idx_idea_outbox_recovery_support_reference;
DROP TABLE IF EXISTS idea_outbox_recovery_audit;
DROP INDEX IF EXISTS idx_idea_outbox_dead_letter_support_reference;
