"""Public domain surface for outbox events, delivery, and recovery."""

from app.domain.outbox.delivery import OutboxDeliveryDecision, OutboxDeliveryResult
from app.domain.outbox.events import (
    OUTBOX_EVENT_AGGREGATE_TYPE,
    OUTBOX_EVENT_SCHEMA_VERSION,
    SUPPORTED_OUTBOX_EVENT_TYPES,
    EventLineageContext,
    EventLineageOrigin,
    OutboxEventRecord,
    OutboxEventStatus,
    build_candidate_outbox_event,
    lease_outbox_event,
    mark_outbox_event_failed,
    mark_outbox_event_published,
    validate_outbox_failure_reason,
)
from app.domain.outbox.recovery import (
    MAX_OUTBOX_RECOVERY_ATTEMPTS,
    OUTBOX_RECOVERY_OWNER,
    OutboxDeadLetterSummary,
    OutboxRecoveryAuditRecord,
    OutboxRecoveryClaimResult,
    OutboxRecoveryDecision,
    build_outbox_recovery_audit_record,
    claim_dead_letter_for_recovery,
    dead_letter_summaries,
    dead_letter_summary,
    outbox_dead_letter_support_reference,
    outbox_recovery_eligibility_blocker,
    outbox_recovery_request_payload,
)

__all__ = [
    "MAX_OUTBOX_RECOVERY_ATTEMPTS",
    "OUTBOX_EVENT_AGGREGATE_TYPE",
    "OUTBOX_EVENT_SCHEMA_VERSION",
    "OUTBOX_RECOVERY_OWNER",
    "SUPPORTED_OUTBOX_EVENT_TYPES",
    "EventLineageContext",
    "EventLineageOrigin",
    "OutboxDeadLetterSummary",
    "OutboxDeliveryDecision",
    "OutboxDeliveryResult",
    "OutboxEventRecord",
    "OutboxEventStatus",
    "OutboxRecoveryAuditRecord",
    "OutboxRecoveryClaimResult",
    "OutboxRecoveryDecision",
    "build_candidate_outbox_event",
    "build_outbox_recovery_audit_record",
    "claim_dead_letter_for_recovery",
    "dead_letter_summaries",
    "dead_letter_summary",
    "lease_outbox_event",
    "mark_outbox_event_failed",
    "mark_outbox_event_published",
    "outbox_dead_letter_support_reference",
    "outbox_recovery_eligibility_blocker",
    "outbox_recovery_request_payload",
    "validate_outbox_failure_reason",
]
