from __future__ import annotations

WORKFLOW_EXPECTATIONS: dict[str, tuple[str, ...]] = {
    "feature-lane.yml": (
        "permissions:\n  contents: read\n  actions: read",
        "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0",
        "actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0",
        "reviewdog/action-actionlint@6fb7acc99f4a1008869fa8a0f09cfca740837d9d # v1.72.0",
        "make lint",
        "make typecheck",
        "make architecture-boundary-gate",
        "make openapi-gate",
        "make security-audit",
        "make test-unit",
        "Feature Lane / CI Signal Evidence",
        "gh api repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/jobs",
        "scripts/ci_signal_evidence.py",
        "feature-lane-ci-signal-evidence",
        "ci-signal-evidence.json",
    ),
    "pr-merge-gate.yml": (
        "permissions:\n  contents: read\n  actions: read",
        "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0",
        "actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0",
        "reviewdog/action-actionlint@6fb7acc99f4a1008869fa8a0f09cfca740837d9d # v1.72.0",
        "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1",
        "actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1",
        "docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0",
        "suite: unit",
        "suite: integration",
        "suite: e2e",
        "make test-${{ matrix.suite }}-coverage",
        "make lint",
        "make typecheck",
        "make architecture-boundary-gate",
        "make openapi-gate",
        "make security-audit",
        "make coverage-gate COVERAGE_DATA_DIR=coverage-data",
        "PostgreSQL Runtime Proof",
        "postgres:18-alpine",
        "LOTUS_IDEA_POSTGRES_INTEGRATION_REQUIRED",
        "LOTUS_IDEA_POSTGRES_INTEGRATION_URL",
        "make postgres-integration-gate",
        "make docker-build",
        'CONTAINER_BASE_IMAGE: "python:3.12-slim"',
        'TRIVY_IMAGE: "aquasec/trivy:0.71.2"',
        "make container-runtime-smoke",
        "make container-image-scan",
        "NODE_OPTIONS: --no-deprecation",
        "PR Merge Gate / CI Signal Evidence",
        "gh api repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/jobs",
        "scripts/ci_signal_evidence.py",
        "pr-merge-gate-ci-signal-evidence",
        "ci-signal-evidence.json",
    ),
    "main-releasability.yml": (
        "workflow_dispatch:",
        "merged-pr-main-releasability.yml as the authoritative",
        "permissions:\n  contents: read\n  actions: read",
        "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0",
        "actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0",
        "reviewdog/action-actionlint@6fb7acc99f4a1008869fa8a0f09cfca740837d9d # v1.72.0",
        "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1",
        "actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1",
        "docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0",
        "suite: unit",
        "suite: integration",
        "suite: e2e",
        "make test-${{ matrix.suite }}-coverage",
        "make lint",
        "make typecheck",
        "make architecture-boundary-gate",
        "make openapi-gate",
        "make security-audit",
        "make coverage-gate COVERAGE_DATA_DIR=coverage-data",
        "PostgreSQL Runtime Proof",
        "postgres:18-alpine",
        "LOTUS_IDEA_POSTGRES_INTEGRATION_REQUIRED",
        "LOTUS_IDEA_POSTGRES_INTEGRATION_URL",
        "make postgres-integration-gate",
        "make docker-build",
        'CONTAINER_IMAGE_NAME: "backend-service:ci-test"',
        'CONTAINER_BASE_IMAGE: "python:3.12-slim"',
        'TRIVY_IMAGE: "aquasec/trivy:0.71.2"',
        "make container-runtime-smoke",
        "make container-image-scan",
        "Resolve container image provenance",
        'docker image inspect "$CONTAINER_IMAGE_NAME"',
        "CONTAINER_IMAGE_ID",
        'docker pull "$CONTAINER_BASE_IMAGE"',
        'docker image inspect "$CONTAINER_BASE_IMAGE"',
        'docker pull "$TRIVY_IMAGE"',
        'docker image inspect "$TRIVY_IMAGE"',
        "CONTAINER_BASE_IMAGE_DIGEST",
        "TRIVY_IMAGE_DIGEST",
        "make release-sbom",
        "sbom.cdx.json",
        "            output/security/container-image-scan.trivy.json",
        "cyclonedx-bom==7.3.0",
        "aquasec/trivy:0.71.2",
        "release-evidence.json",
        '"container_image": os.environ["CONTAINER_IMAGE_NAME"]',
        '"container_image_id": os.environ["CONTAINER_IMAGE_ID"]',
        '"docker_base_image": os.environ["CONTAINER_BASE_IMAGE"]',
        '"docker_base_image_resolved_digest": os.environ[',
        '"sboms": [',
        '"scope": "runtime_python_dependencies"',
        '"target_artifact": os.environ["CONTAINER_IMAGE_NAME"]',
        '"target_artifact_id": os.environ["CONTAINER_IMAGE_ID"]',
        '"dependency_source": "requirements/runtime-resolved.lock.txt"',
        '"project_metadata": "pyproject.toml"',
        '"generator": "cyclonedx-bom==7.3.0"',
        '"container_scanner": os.environ["TRIVY_IMAGE"]',
        '"container_scanner_resolved_digest": os.environ[',
        '"ci_signal_evidence_path": "ci-signal-evidence.json"',
        '"ci_signal_evidence_artifact": "main-releasability-ci-signal-evidence"',
        "main-releasability-release-evidence",
        "NODE_OPTIONS: --no-deprecation",
        "Main Releasability / CI Signal Evidence",
        "gh api repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/jobs",
        "scripts/ci_signal_evidence.py",
        "main-releasability-ci-signal-evidence",
        "ci-signal-evidence.json",
    ),
    "pr-auto-merge.yml": (
        "pull_request_target:",
        "contents: read",
        "github.event.pull_request.head.repo.fork == false",
        "secrets.LOTUS_AUTOMERGE_TOKEN",
        "LOTUS_AUTOMERGE_TOKEN is required",
        "Resource not accessible by personal access token",
        "gh pr merge",
        "--auto --rebase --delete-branch",
    ),
    "merged-pr-main-releasability.yml": (
        "pull_request_target:",
        "types: [closed]",
        "actions: write",
        "contents: read",
        "github.event.pull_request.merged == true",
        "github.event.pull_request.base.ref == 'main'",
        "gh workflow run main-releasability.yml",
        "--ref main",
    ),
}

PROHIBITED_WORKFLOW_PATTERNS: dict[str, tuple[str, ...]] = {
    "feature-lane.yml": (
        "pull_request_target:",
        "contents: write",
        "pull-requests: write",
        "continue-on-error:",
        "run: ./.venv/bin/python -m pytest",
        "coverage combine coverage-data",
        "coverage report --fail-under=99",
        "pip install cyclonedx-bom",
    ),
    "pr-merge-gate.yml": (
        "pull_request_target:",
        "contents: write",
        "pull-requests: write",
        "continue-on-error:",
        "run: ./.venv/bin/python -m pytest",
        "coverage combine coverage-data",
        "coverage report --fail-under=99",
        "pip install cyclonedx-bom",
    ),
    "main-releasability.yml": (
        "  push:",
        "pull_request_target:",
        "contents: write",
        "pull-requests: write",
        "continue-on-error:",
        "run: ./.venv/bin/python -m pytest",
        "coverage combine coverage-data",
        "coverage report --fail-under=99",
        "pip install cyclonedx-bom",
    ),
    "pr-auto-merge.yml": ("continue-on-error:",),
    "merged-pr-main-releasability.yml": ("continue-on-error:",),
}
