from __future__ import annotations

from datetime import date
import hashlib
from pathlib import Path
import re
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
POLICY_PATH = Path("contracts/compliance/lotus-idea-license-policy.v1.json")
PACKAGE = re.compile(r"^(?P<name>[A-Za-z0-9_.-]+)==(?P<version>[^\s;]+)")
SPDX_TOKEN = re.compile(r"[A-Za-z0-9][A-Za-z0-9.+-]*")
SPDX_OPERATORS = {"AND", "OR", "WITH"}
EXCEPTION_ID = re.compile(r"^LIC-EX-[0-9]{3,}$")


def validate_license_policy(
    payload: dict[str, Any],
    *,
    repository_root: Path = ROOT,
    as_of_date: date | None = None,
) -> list[str]:
    errors = _validate_header(payload)
    locks, lock_errors = _load_governed_locks(payload, repository_root)
    errors.extend(lock_errors)
    effective_date = as_of_date or date.today()
    errors.extend(_validate_exceptions(payload, effective_date))
    errors.extend(_validate_components(payload, locks, effective_date))
    errors.extend(_validate_external_and_asset_posture(payload))
    notice_path = payload.get("notice_path")
    if isinstance(notice_path, str):
        expected_notice = render_third_party_notice(payload)
        path = repository_root / notice_path
        if not path.exists() or path.read_text(encoding="utf-8") != expected_notice:
            errors.append("third-party NOTICE must match deterministic policy output")
    else:
        errors.append("license policy notice_path is required")
    return errors


def render_third_party_notice(payload: dict[str, Any]) -> str:
    components = payload.get("components")
    rows = (
        sorted(
            (component for component in components if isinstance(component, dict)),
            key=lambda item: _canonical_name(str(item.get("name", ""))),
        )
        if isinstance(components, list)
        else []
    )
    lines = [
        "# Third-Party Notices",
        "",
        "Generated from `contracts/compliance/lotus-idea-license-policy.v1.json`.",
        "Do not edit this file independently of the governed policy.",
        "",
        "| Component | Version | Scope | SPDX | Source | Conditional obligations |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for component in rows:
        obligations = component.get("obligations")
        obligation_text = ", ".join(str(item) for item in obligations) if obligations else "None"
        scopes = ", ".join(str(item) for item in component.get("scopes", []))
        lines.append(
            f"| `{component.get('name')}` | `{component.get('version')}` | {scopes} | "
            f"`{component.get('spdx')}` | {component.get('source_url')} | {obligation_text} |"
        )
    lines.extend(
        [
            "",
            "## Service And Asset Posture",
            "",
            f"Lotus Idea service code: `{payload.get('service_license')}`.",
            "External base/scanner images and generated/model/data assets are governed by the "
            "policy contract; consult it for ownership and non-proof boundaries.",
            "",
        ]
    )
    return "\n".join(lines)


def validate_release_license_evidence(
    policy: dict[str, Any],
    manifest: dict[str, Any],
    sbom: dict[str, Any],
    *,
    repository_root: Path = ROOT,
) -> list[str]:
    evidence = manifest.get("license_compliance")
    if not isinstance(evidence, dict):
        return ["release manifest license_compliance evidence is required"]
    notice_path = policy.get("notice_path")
    notice_digest = None
    if isinstance(notice_path, str) and (repository_root / notice_path).exists():
        notice_digest = hashlib.sha256((repository_root / notice_path).read_bytes()).hexdigest()
    expected = {
        "policy_contract": "contracts/compliance/lotus-idea-license-policy.v1.json",
        "policy_version": policy.get("contract_version"),
        "runtime_lock_sha256": _nested(policy, "runtime_lock", "sha256"),
        "ci_lock_sha256": _nested(policy, "ci_lock", "sha256"),
        "notice_path": notice_path,
        "notice_sha256": notice_digest,
        "sbom_serial_number": sbom.get("serialNumber"),
        "exception_ids": sorted(
            str(item.get("exception_id"))
            for item in policy.get("exceptions", [])
            if isinstance(item, dict)
        ),
        "target_artifact": manifest.get("container_image_digest_reference"),
    }
    return [
        f"release license evidence {key} must match policy/SBOM/artifact"
        for key, value in expected.items()
        if evidence.get(key) != value
    ]


def _validate_header(payload: dict[str, Any]) -> list[str]:
    expected = {
        "contract_id": "lotus-idea-license-policy",
        "contract_version": "1.0.0",
        "service_license": "LicenseRef-Lotus-Proprietary",
    }
    errors = [
        f"license policy {key} must be {value!r}"
        for key, value in expected.items()
        if payload.get(key) != value
    ]
    approval = payload.get("approval")
    if not isinstance(approval, dict) or approval.get("policy_change_review_required") is not True:
        errors.append("license policy changes must require explicit owner/legal/security review")
    else:
        required_owners = {"lotus-idea-owners", "security", "legal"}
        if set(approval.get("owners", [])) != required_owners:
            errors.append("license policy approval owners must include app, security, and legal")
        if set(approval.get("required_exception_approvals", [])) != required_owners:
            errors.append("license exceptions must require app, security, and legal approval")
        if approval.get("exception_expiry_required") is not True:
            errors.append("license exceptions must require expiry")
        if approval.get("approval_evidence_required") is not True:
            errors.append("license approvals must require durable evidence")
        if approval.get("approval_evidence_format") != "immutable_review_or_ticket_reference":
            errors.append(
                "license approval evidence must use an immutable review or ticket reference"
            )
        if approval.get("repository_review_routing") != ".github/CODEOWNERS":
            errors.append("license policy must declare repository review routing")
    return errors


def _load_governed_locks(
    payload: dict[str, Any], repository_root: Path
) -> tuple[dict[str, dict[str, str]], list[str]]:
    locks: dict[str, dict[str, str]] = {}
    errors: list[str] = []
    for scope, key in (("runtime", "runtime_lock"), ("ci", "ci_lock")):
        contract = payload.get(key)
        if not isinstance(contract, dict):
            errors.append(f"license policy {key} is required")
            continue
        relative_path = contract.get("path")
        if (
            not isinstance(relative_path, str)
            or Path(relative_path).is_absolute()
            or ".." in Path(relative_path).parts
        ):
            errors.append(f"license policy {key}.path must be repository-relative")
            continue
        path = repository_root / relative_path
        if not path.exists():
            errors.append(f"license policy {key}.path does not exist")
            continue
        content = path.read_bytes()
        if hashlib.sha256(content).hexdigest() != contract.get("sha256"):
            errors.append(f"license policy {key} hash does not match the resolved lock")
        locks[scope] = _parse_lock(content.decode("utf-8"))
    return locks, errors


def _validate_components(
    payload: dict[str, Any], locks: dict[str, dict[str, str]], as_of_date: date
) -> list[str]:
    components = payload.get("components")
    if not isinstance(components, list):
        return ["license policy components must be a list"]
    errors: list[str] = []
    observed: dict[tuple[str, str], dict[str, Any]] = {}
    for component in components:
        if not isinstance(component, dict):
            errors.append("license policy component entries must be objects")
            continue
        name = _canonical_name(str(component.get("name", "")))
        version = str(component.get("version", ""))
        for scope in component.get("scopes", []):
            key = (str(scope), name)
            if key in observed:
                errors.append(f"duplicate license inventory component {scope}:{name}")
            observed[key] = component
        errors.extend(_validate_component_policy(component, payload, as_of_date))
        if not version:
            errors.append(f"license inventory component {name} version is required")
    expected = {
        (scope, name): version
        for scope, entries in locks.items()
        for name, version in entries.items()
    }
    for key, version in expected.items():
        component = observed.get(key)
        if component is None:
            errors.append(f"license inventory missing locked component {key[0]}:{key[1]}")
        elif component.get("version") != version:
            errors.append(f"license inventory version drift for {key[0]}:{key[1]}")
    for key in sorted(set(observed) - set(expected)):
        errors.append(f"license inventory contains unlocked component {key[0]}:{key[1]}")
    return errors


def _validate_exceptions(payload: dict[str, Any], as_of_date: date) -> list[str]:
    exceptions = payload.get("exceptions")
    if not isinstance(exceptions, list):
        return ["license policy exceptions must be a list"]
    components = payload.get("components")
    component_entries = components if isinstance(components, list) else []
    component_licenses = {
        _canonical_name(str(component.get("name", ""))): _license_tokens(
            str(component.get("spdx", ""))
        )
        for component in component_entries
        if isinstance(component, dict)
    }
    errors: list[str] = []
    seen_ids: set[str] = set()
    required_approvers = {"lotus-idea-owners", "security", "legal"}
    for exception in exceptions:
        if not isinstance(exception, dict):
            errors.append("license exception entries must be objects")
            continue
        exception_id = str(exception.get("exception_id", ""))
        if not EXCEPTION_ID.fullmatch(exception_id):
            errors.append("license exception_id must match LIC-EX-NNN")
        elif exception_id in seen_ids:
            errors.append(f"duplicate license exception_id {exception_id}")
        seen_ids.add(exception_id)
        component = _canonical_name(str(exception.get("component", "")))
        expression = str(exception.get("spdx", ""))
        if component not in component_licenses:
            errors.append(f"license exception {exception_id} component must be inventoried")
        elif expression not in component_licenses[component]:
            errors.append(f"license exception {exception_id} SPDX must match the component")
        approved_by = exception.get("approved_by")
        if not isinstance(approved_by, list) or set(approved_by) != required_approvers:
            errors.append(f"license exception {exception_id} requires all approval roles")
        evidence_ref = exception.get("approval_evidence_ref")
        if not isinstance(evidence_ref, str) or not evidence_ref.startswith("https://"):
            errors.append(f"license exception {exception_id} requires immutable approval evidence")
        reason = exception.get("reason")
        if not isinstance(reason, str) or not reason.strip():
            errors.append(f"license exception {exception_id} requires a bounded reason")
        try:
            expires = date.fromisoformat(str(exception.get("expires_on")))
        except ValueError:
            errors.append(f"license exception {exception_id} requires an ISO expiry date")
        else:
            if expires < as_of_date:
                errors.append(f"license exception {exception_id} is expired")
    return errors


def _validate_component_policy(
    component: dict[str, Any], payload: dict[str, Any], as_of_date: date
) -> list[str]:
    name = _canonical_name(str(component.get("name", "")))
    errors: list[str] = []
    source_url = component.get("source_url")
    if not isinstance(source_url, str) or not source_url.startswith("https://"):
        errors.append(f"license inventory source URL is required for {name}")
    if component.get("attribution_status") != "included":
        errors.append(f"license attribution must be included for {name}")
    policy = payload.get("policy")
    if not isinstance(policy, dict):
        return errors + ["license classification policy is required"]
    expressions = _license_tokens(str(component.get("spdx", "")))
    approved = set(policy.get("approved", []))
    conditional = set(policy.get("conditional", []))
    denied = set(policy.get("denied", []))
    for expression in expressions:
        if expression in denied or expression not in approved | conditional:
            if not _has_active_exception(payload, name, expression, as_of_date):
                errors.append(f"license {expression or 'UNKNOWN'} is not approved for {name}")
    if conditional.intersection(expressions) and not component.get("obligations"):
        errors.append(f"conditional license obligations are required for {name}")
    return errors


def _validate_external_and_asset_posture(payload: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    external = payload.get("external_components")
    if not isinstance(external, list) or {
        item.get("name") for item in external if isinstance(item, dict)
    } != {"python-base-image", "trivy-scanner"}:
        errors.append("license policy must classify governed base and scanner images")
    assets = payload.get("asset_inventory")
    if (
        not isinstance(assets, dict)
        or assets.get("posture") != "no_external_generated_model_or_data_assets_distributed"
    ):
        errors.append("license policy must declare generated, model, and data asset posture")
    return errors


def _has_active_exception(
    payload: dict[str, Any], component: str, expression: str, as_of_date: date
) -> bool:
    exceptions = payload.get("exceptions")
    if not isinstance(exceptions, list):
        return False
    for exception in exceptions:
        if not isinstance(exception, dict):
            continue
        approved_by = exception.get("approved_by")
        try:
            expires = date.fromisoformat(str(exception.get("expires_on")))
        except ValueError:
            continue
        if (
            exception.get("component") == component
            and exception.get("spdx") == expression
            and isinstance(approved_by, list)
            and set(approved_by) == {"lotus-idea-owners", "security", "legal"}
            and isinstance(exception.get("approval_evidence_ref"), str)
            and str(exception.get("approval_evidence_ref")).strip() != ""
            and isinstance(exception.get("reason"), str)
            and str(exception.get("reason")).strip() != ""
            and expires >= as_of_date
        ):
            return True
    return False


def _parse_lock(content: str) -> dict[str, str]:
    packages: dict[str, str] = {}
    for line in content.splitlines():
        match = PACKAGE.match(line.strip())
        if match:
            packages[_canonical_name(match.group("name"))] = match.group("version")
    return packages


def _canonical_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def _nested(payload: dict[str, Any], section: str, key: str) -> object:
    value = payload.get(section)
    return value.get(key) if isinstance(value, dict) else None


def _license_tokens(expression: str) -> set[str]:
    return {token for token in SPDX_TOKEN.findall(expression) if token not in SPDX_OPERATORS}
