from __future__ import annotations

from typing import Any, Protocol, Sequence


class PostgresCursor(Protocol):
    def execute(self, query: str, params: Sequence[Any] | None = None) -> Any: ...
    def fetchall(self) -> Sequence[Any]: ...
    def __enter__(self) -> PostgresCursor: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...


class PostgresConnection(Protocol):
    def cursor(self) -> PostgresCursor: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
